/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import Connections.ConnectionDB;

/**
 *
 * @author Dinopc
 */
public class estoqueConsulta extends javax.swing.JInternalFrame {
    /**
     * Creates new form clientesCadastro
     */
    public estoqueConsulta() {
        initComponents();
        this.setMaximizable(false);
        this.setClosable(true);
        this.setResizable(true);
        this.setIconifiable(true);
        this.setTitle("Consulta Estoque");
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        painelTelaPrincipalEstoqueConsulta = new javax.swing.JPanel();
        inputPesquisaEstoqueConsulta = new javax.swing.JTextField();
        botaoPesquisaEstoqueConsulta = new javax.swing.JButton();
        painelTabelaClientesConsulta = new javax.swing.JPanel();
        scrollTabelaClientesConsulta = new javax.swing.JScrollPane();
        tabelaEstoqueConsulta = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setTitle("Consulta Estoque");
        setMaximumSize(new java.awt.Dimension(620, 550));
        setMinimumSize(new java.awt.Dimension(620, 550));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(620, 550));
        setVisible(false);

        painelTelaPrincipalEstoqueConsulta.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        painelTelaPrincipalEstoqueConsulta.setMaximumSize(new java.awt.Dimension(620, 500));
        painelTelaPrincipalEstoqueConsulta.setMinimumSize(new java.awt.Dimension(620, 500));
        painelTelaPrincipalEstoqueConsulta.setPreferredSize(new java.awt.Dimension(620, 500));

        inputPesquisaEstoqueConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPesquisaEstoqueConsultaActionPerformed(evt);
            }
        });

        botaoPesquisaEstoqueConsulta.setBackground(new java.awt.Color(43, 82, 253));
        botaoPesquisaEstoqueConsulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/clientes.png"))); // NOI18N
        botaoPesquisaEstoqueConsulta.setText("Pesquisa");
        botaoPesquisaEstoqueConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisaEstoqueConsultaActionPerformed(evt);
            }
        });

        tabelaEstoqueConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CodCategoria", "Nome produto", "Preço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        scrollTabelaClientesConsulta.setViewportView(tabelaEstoqueConsulta);

        javax.swing.GroupLayout painelTabelaClientesConsultaLayout = new javax.swing.GroupLayout(painelTabelaClientesConsulta);
        painelTabelaClientesConsulta.setLayout(painelTabelaClientesConsultaLayout);
        painelTabelaClientesConsultaLayout.setHorizontalGroup(
            painelTabelaClientesConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollTabelaClientesConsulta)
        );
        painelTabelaClientesConsultaLayout.setVerticalGroup(
            painelTabelaClientesConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTabelaClientesConsultaLayout.createSequentialGroup()
                .addComponent(scrollTabelaClientesConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelTelaPrincipalEstoqueConsultaLayout = new javax.swing.GroupLayout(painelTelaPrincipalEstoqueConsulta);
        painelTelaPrincipalEstoqueConsulta.setLayout(painelTelaPrincipalEstoqueConsultaLayout);
        painelTelaPrincipalEstoqueConsultaLayout.setHorizontalGroup(
            painelTelaPrincipalEstoqueConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTelaPrincipalEstoqueConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelTelaPrincipalEstoqueConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(painelTabelaClientesConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(painelTelaPrincipalEstoqueConsultaLayout.createSequentialGroup()
                        .addComponent(inputPesquisaEstoqueConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoPesquisaEstoqueConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelTelaPrincipalEstoqueConsultaLayout.setVerticalGroup(
            painelTelaPrincipalEstoqueConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTelaPrincipalEstoqueConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelTelaPrincipalEstoqueConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputPesquisaEstoqueConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoPesquisaEstoqueConsulta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelTabelaClientesConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelTelaPrincipalEstoqueConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 585, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelTelaPrincipalEstoqueConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void botaoPesquisaEstoqueConsultaActionPerformed(java.awt.event.ActionEvent evt) {                                                             
        //defaultTableModel tabelaCliente  = (defaultTableModel) tabelaClientesConsulta.getModel();   
    	// Rodar o evento do input abaixo
    }                                                            

    private void inputPesquisaEstoqueConsultaActionPerformed(java.awt.event.ActionEvent evt) {                                                             
        // TODO add your handling code here:
    	String busca;
    	try {
    		busca = inputPesquisaEstoqueConsulta.getText();
    		
    		ConnectionDB.Conectar();
    		String sql = "select nome_produto,preco_produto,cod_categoria from produtos where nome_produto = ?";
    		PreparedStatement stm = ConnectionDB.preparedStament(sql);
    		stm.setString(1, busca);
    		ResultSet result = ConnectionDB.runPreparedSelect(stm);
    		
    		while ( result.next() ) {
    			System.out.println(result.getString("nome_produto") + " " + result.getFloat("preco_produto") + " " + result.getInt("cod_categoria"));
    		}
    		
    		ConnectionDB.Desconectar();
    	} catch (NumberFormatException e){
    		System.out.println(e);
    	} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    }                                                            


    // Variables declaration - do not modify                     
    private javax.swing.JButton botaoPesquisaEstoqueConsulta;
    private javax.swing.JTextField inputPesquisaEstoqueConsulta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel painelTabelaClientesConsulta;
    private javax.swing.JPanel painelTelaPrincipalEstoqueConsulta;
    private javax.swing.JScrollPane scrollTabelaClientesConsulta;
    private javax.swing.JTable tabelaEstoqueConsulta;
    // End of variables declaration                   

}
