/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

/**
 *
 * @author Dinopc
 */
public class produtosCadastro extends javax.swing.JInternalFrame {
    /**
     * Creates new form clientesCadastro
     */
    public produtosCadastro() {
        initComponents();
        this.setMaximizable(false);
        this.setClosable(true);
        this.setResizable(true);
        this.setIconifiable(true);
        this.setTitle("Cadastro de produtos");
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        painelPrincipalProdutosCadastro = new javax.swing.JPanel();
        txtNomeProduto = new javax.swing.JLabel();
        txtFornecedor = new javax.swing.JLabel();
        txtPreco = new javax.swing.JLabel();
        botaoLimparProdutosCadastro = new javax.swing.JButton();
        botaoSalvarProdutosCadastro = new javax.swing.JButton();
        inputNomeProduto = new javax.swing.JTextField();
        inputFornecedor = new javax.swing.JTextField();
        inputPreco = new javax.swing.JFormattedTextField();
        painelAdicionarImagemProduto = new javax.swing.JPanel();
        txtAdicionarImagemProduto = new javax.swing.JLabel();
        inputCategoria = new javax.swing.JTextField();
        txtCategoria = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setTitle("Cadastro Cliente");
        setMaximumSize(new java.awt.Dimension(620, 550));
        setMinimumSize(new java.awt.Dimension(620, 550));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(620, 550));
        setVisible(false);

        painelPrincipalProdutosCadastro.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        painelPrincipalProdutosCadastro.setMaximumSize(new java.awt.Dimension(620, 500));
        painelPrincipalProdutosCadastro.setMinimumSize(new java.awt.Dimension(620, 500));
        painelPrincipalProdutosCadastro.setPreferredSize(new java.awt.Dimension(620, 500));

        txtNomeProduto.setText("Nome");

        txtFornecedor.setText("Fornecedor");

        txtPreco.setText("Preço");

        botaoLimparProdutosCadastro.setBackground(new java.awt.Color(254, 59, 55));
        botaoLimparProdutosCadastro.setText("Limpar");
        botaoLimparProdutosCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparProdutosCadastroActionPerformed(evt);
            }
        });

        botaoSalvarProdutosCadastro.setBackground(new java.awt.Color(43, 82, 253));
        botaoSalvarProdutosCadastro.setText("Salvar");
        botaoSalvarProdutosCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoSalvarProdutosCadastroActionPerformed(evt);
            }
        });

        inputPreco.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));
        inputPreco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPrecoActionPerformed(evt);
            }
        });

        painelAdicionarImagemProduto.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtAdicionarImagemProduto.setText("Adicionar Imagem Produto");

        javax.swing.GroupLayout painelAdicionarImagemProdutoLayout = new javax.swing.GroupLayout(painelAdicionarImagemProduto);
        painelAdicionarImagemProduto.setLayout(painelAdicionarImagemProdutoLayout);
        painelAdicionarImagemProdutoLayout.setHorizontalGroup(
            painelAdicionarImagemProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAdicionarImagemProdutoLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(txtAdicionarImagemProduto)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        painelAdicionarImagemProdutoLayout.setVerticalGroup(
            painelAdicionarImagemProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelAdicionarImagemProdutoLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(txtAdicionarImagemProduto)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        txtCategoria.setText("Categoria");

        javax.swing.GroupLayout painelPrincipalProdutosCadastroLayout = new javax.swing.GroupLayout(painelPrincipalProdutosCadastro);
        painelPrincipalProdutosCadastro.setLayout(painelPrincipalProdutosCadastroLayout);
        painelPrincipalProdutosCadastroLayout.setHorizontalGroup(
            painelPrincipalProdutosCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalProdutosCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPrincipalProdutosCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPrincipalProdutosCadastroLayout.createSequentialGroup()
                        .addGroup(painelPrincipalProdutosCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(inputCategoria)
                            .addComponent(inputPreco, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(inputFornecedor, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeProduto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFornecedor, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputNomeProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(txtPreco, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(painelPrincipalProdutosCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(painelAdicionarImagemProduto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelPrincipalProdutosCadastroLayout.createSequentialGroup()
                                .addComponent(botaoLimparProdutosCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoSalvarProdutosCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)))
                        .addGap(37, 37, 37))
                    .addGroup(painelPrincipalProdutosCadastroLayout.createSequentialGroup()
                        .addComponent(txtCategoria)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        painelPrincipalProdutosCadastroLayout.setVerticalGroup(
            painelPrincipalProdutosCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalProdutosCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelPrincipalProdutosCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelPrincipalProdutosCadastroLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtNomeProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(txtFornecedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(txtPreco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(painelAdicionarImagemProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(painelPrincipalProdutosCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelPrincipalProdutosCadastroLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtCategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelPrincipalProdutosCadastroLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(painelPrincipalProdutosCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botaoLimparProdutosCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botaoSalvarProdutosCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(186, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelPrincipalProdutosCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 585, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelPrincipalProdutosCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void inputPrecoActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void botaoLimparProdutosCadastroActionPerformed(java.awt.event.ActionEvent evt) {                                                            
    	botaoSalvarProdutosCadastro.setText("");
    	inputCategoria.setText("");
    	inputFornecedor.setText("");
    	inputNomeProduto.setText("");
    	inputPreco.setText("");
    }                                                           

    private void botaoSalvarProdutosCadastroActionPerformed(java.awt.event.ActionEvent evt) {                                                            
    	String categoria;
    	String fornecedor;
    	String nomeProduto;
    	String preco;

    	try {
    		categoria = inputCategoria.getText();
    		System.out.println(categoria);

    		fornecedor = inputFornecedor.getText();
    		System.out.println(fornecedor);

    		nomeProduto = inputNomeProduto.getText();
    		System.out.println(nomeProduto);

    		preco = inputPreco.getText();
    		System.out.println(preco);

            
    	}catch(NumberFormatException e) {
    		
    	}
    	
    }                                                           


    // Variables declaration - do not modify                     
    private javax.swing.JButton botaoLimparProdutosCadastro;
    private javax.swing.JButton botaoSalvarProdutosCadastro;
    private javax.swing.JTextField inputCategoria;
    private javax.swing.JTextField inputFornecedor;
    private javax.swing.JTextField inputNomeProduto;
    private javax.swing.JFormattedTextField inputPreco;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel painelAdicionarImagemProduto;
    private javax.swing.JPanel painelPrincipalProdutosCadastro;
    private javax.swing.JLabel txtAdicionarImagemProduto;
    private javax.swing.JLabel txtCategoria;
    private javax.swing.JLabel txtFornecedor;
    private javax.swing.JLabel txtNomeProduto;
    private javax.swing.JLabel txtPreco;
    // End of variables declaration                   
}
